/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.SoftwarePR.AgendaDeVeiculos.Telas;

import br.com.SoftwarePR.AgendaDeVeiculos.Banco.ConexaoCRUD;
import br.com.SoftwarePR.AgendaDeVeiculos.Construtor.ConstrutorAgenda;

import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author Paulo Ricardo
 */
public class TelaCriarAgenda extends javax.swing.JFrame {

    private String veiculo;
    private String data;
    private String dataChegada;
    private String hora;
    private String horaChegada;
    private String colaborador;
    private String observacao;

    /**
     * Creates new form TelaIncial
     */
    public TelaCriarAgenda() {
        initComponents();
        setLocationRelativeTo(null);
        LimparTela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnMenu = new javax.swing.JButton();
        btnAgendar1 = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        ComboVeiculos = new javax.swing.JComboBox<>();
        ComboDataChegada = new com.toedter.calendar.JDateChooser();
        ComboHoraChegada = new javax.swing.JComboBox<>();
        ComboColaborador = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ComboDataSaida = new com.toedter.calendar.JDateChooser();
        ComboHoraSaida = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxtObservacao = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agenda De Veiculos");
        setBackground(new java.awt.Color(204, 204, 255));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(java.awt.Color.lightGray);
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setToolTipText("");
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("By Software PR");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 350, -1, -1));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Colaborador:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Observação:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, -1, -1));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Data Saída:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Hora Saída:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        btnMenu.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        btnMenu.setText("MENU");
        btnMenu.setToolTipText("");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });
        jPanel1.add(btnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, -1, -1));

        btnAgendar1.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        btnAgendar1.setText("AGENDAR");
        btnAgendar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgendar1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgendar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, -1, -1));

        btnConsultar.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        btnConsultar.setText("CONSULTAR");
        btnConsultar.setToolTipText("");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        jPanel1.add(btnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, -1, -1));

        ComboVeiculos.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        ComboVeiculos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Strada", "Fiorino", "Gol", "Voyage", "Corolla" }));
        jPanel1.add(ComboVeiculos, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 230, -1));
        jPanel1.add(ComboDataChegada, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, 240, -1));

        ComboHoraChegada.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        ComboHoraChegada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "06:00", "06:30", "07:00", "07:30", "08:00", "08:30", "09:00", "09:30", "10:00", "10:30", "11:00", "11:30", "12:00", "12:30", "13:00", "13:30", "14:00", "14:30", "15:00", "15:30", "16:00", "16:30", "17:00", "17:30", "18:00", "18:30", "19:00", "19:30", "20:00", "20:30", "21:00", "21:30", "22:00", "22:30", "23:00", "23:30", "00:00" }));
        jPanel1.add(ComboHoraChegada, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, 240, -1));

        ComboColaborador.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        ComboColaborador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Colaborador1", "Colaborador2", "Colaborador3", "Colaborador4" }));
        jPanel1.add(ComboColaborador, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 210, -1));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Veiculo:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Data Chegada:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, -1, -1));
        jPanel1.add(ComboDataSaida, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 230, -1));

        ComboHoraSaida.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        ComboHoraSaida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "06:00", "06:30", "07:00", "07:30", "08:00", "08:30", "09:00", "09:30", "10:00", "10:30", "11:00", "11:30", "12:00", "12:30", "13:00", "13:30", "14:00", "14:30", "15:00", "15:30", "16:00", "16:30", "17:00", "17:30", "18:00", "18:30", "19:00", "19:30", "20:00", "20:30", "21:00", "21:30", "22:00", "22:30", "23:00", "23:30", "00:00" }));
        jPanel1.add(ComboHoraSaida, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 230, -1));

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Hora Chegada:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, -1, -1));

        TxtObservacao.setColumns(20);
        TxtObservacao.setLineWrap(true);
        TxtObservacao.setRows(5);
        TxtObservacao.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                TxtObservacaoAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(TxtObservacao);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 220, 240, 100));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 380));

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgendar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgendar1ActionPerformed

        //Metodo para Criar e Adicionar os Dados da Agenda no Banco de Dados
        veiculo = ComboVeiculos.getSelectedItem().toString();

        //Criando uma Váriavel do Modo Data para Pergar a Data Escolhida
        //Formatando a Data com o Metodo SimpleDataFormat
        //Salvando os dados na Váriavel data e formatando a dataSelecionada para o Formato Correto
        Date dataSelecionada = ComboDataSaida.getDate();
        SimpleDateFormat dataFormatada = new SimpleDateFormat("dd/MM/yyyy");
        data = dataFormatada.format(dataSelecionada);

        Date dataSelecionadaChegada = ComboDataChegada.getDate();
        SimpleDateFormat dataFormatadaChegada = new SimpleDateFormat("dd/MM/yyyy");
        dataChegada = dataFormatadaChegada.format(dataSelecionadaChegada);

        hora = ComboHoraSaida.getSelectedItem().toString();
        horaChegada = ComboHoraChegada.getSelectedItem().toString();
        colaborador = ComboColaborador.getSelectedItem().toString();
        observacao = TxtObservacao.getText();

        //Chamando a Conexao com o Banco
        ConexaoCRUD BancoDados = new ConexaoCRUD();

        //Adicionado os Dados no Construtor
        ConstrutorAgenda construtor = new ConstrutorAgenda();
        construtor.setVeiculo(veiculo);
        construtor.setData(data);
        construtor.setDatachegada(dataChegada);
        construtor.setHora(hora);
        construtor.setHorachegada(horaChegada);
        construtor.setColaborador(colaborador);
        construtor.setObservacao(observacao);

        //Adicionando os Dados no Banco de Dados
        BancoDados.AdicionarAgenda(construtor);
        
        //Chamando o Método para Limpar as Labels no Aplicativo
        LimparTela();

    }//GEN-LAST:event_btnAgendar1ActionPerformed
    
    //Metodo para Limpara a Tela dos Usuário
    private void LimparTela() {
        ComboVeiculos.setSelectedItem(null);
        ComboDataSaida.setDate(null);
        ComboDataChegada.setDate(null);
        ComboHoraSaida.setSelectedItem(null);
        ComboHoraChegada.setSelectedItem(null);
        ComboColaborador.setSelectedItem(null);
        TxtObservacao.setText("");
    }


    private void TxtObservacaoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_TxtObservacaoAncestorAdded

    }//GEN-LAST:event_TxtObservacaoAncestorAdded

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        TelaMenu menu = new TelaMenu();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        TelaConsultarAgenda consultarAgenda = new TelaConsultarAgenda();
        consultarAgenda.setVisible(true);

        this.dispose();

    }//GEN-LAST:event_btnConsultarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCriarAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCriarAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCriarAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCriarAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCriarAgenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboColaborador;
    private com.toedter.calendar.JDateChooser ComboDataChegada;
    private com.toedter.calendar.JDateChooser ComboDataSaida;
    private javax.swing.JComboBox<String> ComboHoraChegada;
    private javax.swing.JComboBox<String> ComboHoraSaida;
    private javax.swing.JComboBox<String> ComboVeiculos;
    private javax.swing.JTextArea TxtObservacao;
    private javax.swing.JButton btnAgendar1;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
