/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.SoftwarePR.AgendaDeVeiculos.Telas;

import br.com.SoftwarePR.AgendaDeVeiculos.Banco.ConexaoCRUD;
import br.com.SoftwarePR.AgendaDeVeiculos.Construtor.ConstrutorAgenda;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Paulo Ricardo
 */
public class TelaConsultarAgenda extends javax.swing.JFrame {

    private String data;

    /**
     * Creates new form TelaConsultarAgenda
     */
    public TelaConsultarAgenda() {
        initComponents();
        //Chamando a Função de Listar todos os dados que estão no Banco de Dados
        listarDados();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtColaborador = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        txtDataPesquisa = new com.toedter.calendar.JDateChooser();
        btnConsultar = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();
        btnAgendar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaConsulta = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agenda De Veiculos");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("By Software PR");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 380, -1, -1));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Veículo:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 8, -1, -1));

        txtColaborador.setFont(new java.awt.Font("Microsoft JhengHei", 1, 12)); // NOI18N
        txtColaborador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Strada", "Fiorino", "Gol", "Voyage", "Corolla" }));
        jPanel1.add(txtColaborador, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 8, 190, -1));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Data:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 11, -1, -1));

        txtDataPesquisa.setToolTipText("");
        jPanel1.add(txtDataPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 8, 215, -1));

        btnConsultar.setFont(new java.awt.Font("Microsoft JhengHei", 1, 12)); // NOI18N
        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        jPanel1.add(btnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(561, 8, -1, -1));

        btnMenu.setFont(new java.awt.Font("Microsoft JhengHei", 1, 12)); // NOI18N
        btnMenu.setText("Menu");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });
        jPanel1.add(btnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(667, 8, -1, -1));

        btnAgendar.setFont(new java.awt.Font("Microsoft JhengHei", 1, 12)); // NOI18N
        btnAgendar.setText("Agendar");
        btnAgendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgendarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(757, 8, -1, -1));

        jScrollPane1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jScrollPane1ComponentHidden(evt);
            }
        });

        TabelaConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Veículo", "Data Saída", "Hora Saída", "Data Chegada", "Hora Chegada", "Colaborador", "Observação"
            }
        ));
        TabelaConsulta.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                TabelaConsultaAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(TabelaConsulta);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 830, 330));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        //Chamando a Tela de Menu
        
        TelaMenu menu = new TelaMenu();
        menu.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnAgendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgendarActionPerformed
        //Chamndo a Tela de Criar Agenda
        
        TelaCriarAgenda criar = new TelaCriarAgenda();
        criar.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_btnAgendarActionPerformed

    private void TabelaConsultaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_TabelaConsultaAncestorAdded

    }//GEN-LAST:event_TabelaConsultaAncestorAdded

    private void jScrollPane1ComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jScrollPane1ComponentHidden

    }//GEN-LAST:event_jScrollPane1ComponentHidden
    
    
    //Metodo do Botão de Fitro
    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        
        //Pegando a Data Digitada pelo Usuário
        Date dataSelecionada = txtDataPesquisa.getDate();
        
        //Veriificando se foi preenchida Data ou Não
        if (dataSelecionada == null) {
            JOptionPane.showMessageDialog(null, "Selecione uma Data para o Filtro.");

        } else {
            //Formatando as Datas
            SimpleDateFormat dataFormatadaChegada = new SimpleDateFormat("dd/MM/yyyy");
            data = dataFormatadaChegada.format(dataSelecionada);
            
            String DataFiltro = "%" + data + "%";
            
            //Pegando o Veiculo Selecionado Pelo Usuário
            String colaborador = "%" + txtColaborador.getSelectedItem().toString() + "%";
               
            //Chamando a Conexao com o Banco de dados
            ConexaoCRUD banco = new ConexaoCRUD();

            List<ConstrutorAgenda> lista = banco.ConsutarComFiltro(colaborador, DataFiltro);
            
            //Verificando se a conexão da Consulta do Banco de dados é Vazia ou não
            //Se for Vazia vai aparecer uma mensagem para o Usuário
            //E vai chamar o Metodo de listar todas as datas que o mesmo veiculo tem agendada
            if (lista.size()<=0) {
                JOptionPane.showMessageDialog(null, "Nenhum Resultado Encontrado");
                listarFiltroVeiculos();
            
            //Se existir registro dentro daquela data vai ser mostrado para o Usuário
            } else {
                DefaultTableModel dados = (DefaultTableModel) TabelaConsulta.getModel();

                dados.setNumRows(0);

                for (ConstrutorAgenda linha : lista) {

                    dados.addRow(new Object[]{
                        linha.getVeiculo(),
                        linha.getData(),
                        linha.getHora(),
                        linha.getDatachegada(),
                        linha.getHorachegada(),
                        linha.getColaborador(),
                        linha.getObservacao()
                    });

                }
            }

        }


    }//GEN-LAST:event_btnConsultarActionPerformed
    
    
    //Metodo para Lista todo o Banco de Dados
    private void listarDados() {

        ConexaoCRUD banco = new ConexaoCRUD();

        List<ConstrutorAgenda> lista = banco.Consutar();

        DefaultTableModel dados = (DefaultTableModel) TabelaConsulta.getModel();

        dados.setNumRows(0);

        for (ConstrutorAgenda linha : lista) {
            dados.addRow(new Object[]{
                linha.getVeiculo(),
                linha.getData(),
                linha.getHora(),
                linha.getDatachegada(),
                linha.getHorachegada(),
                linha.getColaborador(),
                linha.getObservacao()
            });
        }

    }
    
    //Metodo para listar o Veiculo Especifico
    public void listarFiltroVeiculos(){
        
        String veiculo= txtColaborador.getSelectedItem().toString();
        
        ConexaoCRUD banco = new ConexaoCRUD();

        List<ConstrutorAgenda> lista = banco.ConsutarComFiltroVeiculos(veiculo);

        DefaultTableModel dados = (DefaultTableModel) TabelaConsulta.getModel();

        dados.setNumRows(0);

        for (ConstrutorAgenda linha : lista) {
            dados.addRow(new Object[]{
                linha.getVeiculo(),
                linha.getData(),
                linha.getHora(),
                linha.getDatachegada(),
                linha.getHorachegada(),
                linha.getColaborador(),
                linha.getObservacao()
            });
        }
        
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaConsultarAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaConsultarAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaConsultarAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaConsultarAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaConsultarAgenda().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabelaConsulta;
    private javax.swing.JButton btnAgendar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> txtColaborador;
    private com.toedter.calendar.JDateChooser txtDataPesquisa;
    // End of variables declaration//GEN-END:variables
}
